"""Write ../CUE_SHEET.md (music + effects against the beats, 1x and master times), ../final/loudnorm-report.md and
build/chapters.json, all from the data the mix and the edit actually used (build/cuesheet.json, timeline.json,
build/loudnorm.json). Master times = 1x times / 1.28."""
import json, os

HERE = os.path.dirname(os.path.abspath(__file__))
EP = os.path.abspath(os.path.join(HERE, '..'))
B = os.path.join(EP, 'build')
TL = json.load(open(os.path.join(HERE, 'timeline.json')))
CS = json.load(open(os.path.join(B, 'cuesheet.json')))
LN = json.load(open(os.path.join(B, 'loudnorm.json')))
SP = LN.get('speed', 1.28)
CH = TL['chunks']
MK = TL['marks']


def tc(x, frac=True):
    x = max(0.0, x)
    return f'{int(x // 60)}:{x % 60:05.2f}' if frac else f'{int(x // 60)}:{int(x % 60):02d}'


def m(x, frac=True):
    return tc(x / SP, frac)


CHAPTERS = [
    (0.0, 'Australia’s most famous defeat'),
    (MK['act1'], 'The back door to Germany'),
    (MK['act2'], 'The landing'),
    (MK['act3'], 'What if they’d won?'),
    (MK['act4'], 'The twist'),
]
json.dump([{'t1x': t, 'master': t / SP, 'title': n} for t, n in CHAPTERS], open(os.path.join(B, 'chapters.json'), 'w'), indent=1)

L = ['# Cue sheet — lf02 IF AUSTRALIA… Episode 2', '',
     'What If Australia Had WON at Gallipoli? Generated by `render/gen_docs.py` from the cues the mix used (`render/mix.py`), so the sheet and the mix cannot drift apart.', '',
     f'**Master** = the delivered file, the whole film at {SP}× speed with pitch held. **1×** = the cut, as Whispered and mixed. Master time = 1× time ÷ {SP}.', '',
     '## Markers', '', '| Marker | Master | 1× |', '|---|---|---|']
for t, n in CHAPTERS:
    L.append(f'| Chapter: {n} | {m(t)} | {tc(t)} |')
L.append(f"| Title “IF AUSTRALIA…” + series sting | {m(MK['title'])} | {tc(MK['title'])} |")
L.append(f"| Mid-roll 1 (picture hold after V21; no ad read) | {m(MK['midroll1'])} | {tc(MK['midroll1'])} |")
L.append(f"| Mid-roll 2 (picture hold after V27; no ad read) | {m(MK['midroll2'])} | {tc(MK['midroll2'])} |")
L.append(f"| End screen (10 s, badge stays) | {m(MK['endScreen'])} | {tc(MK['endScreen'])} |")
L.append(f"| End of film | {m(TL['duration'])} | {tc(TL['duration'])} |")
L += ['', '## Voice (Atlas, 37 seated takes, untouched)', '', '| Chunk | Master in | Master out | 1× in | 1× out | Gap before | Note |', '|---|---|---|---|---|---|---|']
for k, c in CH.items():
    note = c['why'] if c['why'] != 'seam' else '0.4 s breath seam'
    if k == 'V27':
        note += '; take plays 0–3.70 s + 8.20 s–end (skips a spoken delivery instruction)'
    if k == 'V31':
        note += '; take plays from 2.10 s (skips the spoken words “Australian accent.”)'
    L.append(f"| {k} | {m(c['start'])} | {m(c['end'])} | {tc(c['start'])} | {tc(c['end'])} | {c['gapBefore']:.1f} s | {note} |")
L += ['', '## Music (Mixkit, Mixkit Stock Music Free Licence)', '', '| Master in | Master out | 1× in | 1× out | File and section | Emotion / beat |', '|---|---|---|---|---|---|']
for kind, t0, t1, what, label, beat in sorted([c for c in CS if c[0] == 'music'], key=lambda c: c[1]):
    L.append(f'| {m(t0)} | {m(t1)} | {tc(t0)} | {tc(t1)} | {what} | {label} ({beat}) |')
L += ['', '## Effects and environment', '', 'All from `audio/sfx/` (in-house, synthesised; see `SOURCES.md`). Environment beds sit only under shots that show them. Every B-roll clip is muted.', '',
      '| Master | 1× | Bus | File | What |', '|---|---|---|---|---|']
for kind, t0, t1, what, label, beat in sorted([c for c in CS if c[0] in ('sfx', 'amb')], key=lambda c: c[1]):
    L.append(f'| {m(t0)} | {tc(t0)} | {kind} | {what} | {label} — {beat} |')
L += ['', '## Picture-sync hits', '', 'Pin drops, label clicks and counter ticks. Each sits in a gap between words or on the cut; hits that would have landed on a word were moved off it (noted) or left out.', '',
      '| Master | 1× | File | What |', '|---|---|---|---|']
for kind, t0, t1, what, label, beat in sorted([c for c in CS if c[0] == 'sync'], key=lambda c: c[1]):
    L.append(f'| {m(t0)} | {tc(t0)} | {what} | {label} |')
L += ['', '## B-roll (33 clips, muted) and full-screen photos', '', '| ID | Master in | 1× in | 1× out | Length / Part 3 | Entry → exit | Pin |', '|---|---|---|---|---|---|---|']
for b in TL['broll']:
    L.append(f"| {b['id']} | {m(b['tIn'])} | {tc(b['tIn'])} | {tc(b['tOut'])} | {b['dur']:.1f} s / {b['part3']} s | {b['entry']} → {b['exit']} | {b['pin']} |")
for k in TL['kb']:
    L.append(f"| {k['id']} (Ken Burns) | {m(k['t0'])} | {tc(k['t0'])} | {tc(k['t1'])} | {k['visible']:.1f} s full-screen | dissolve | — |")
open(os.path.join(EP, 'CUE_SHEET.md'), 'w').write('\n'.join(L) + '\n')

v = LN['verify_master']
R = ['# Loudnorm report — final/lf02-gallipoli.mp4', '',
     f"Measured on the {SP}× pitch-held master audio (`build/master_speed.wav`, the stream muxed into the mp4).", '',
     '| Measure | Value | Target |', '|---|---|---|',
     f"| Integrated loudness | {float(v['input_i']):.1f} LUFS | about −14 LUFS |",
     f"| True peak | {float(v['input_tp']):.1f} dBTP | at or under −1.5 dBTP |",
     f"| Loudness range | {float(v['input_lra']):.1f} LU | — |", '',
     '## Chain', '',
     f"1. Voice takes placed untouched (no loudnorm, no stretch, one static unity gain). Assembled voice: {LN['vo_lufs_untouched']:.1f} LUFS.",
     f"2. Mix at 1× (`render/mix.py`): music beds ducked under the voice, environment and sync hits; pre-master {LN.get('premaster_1x_lufs', 0):.1f} LUFS.",
     f"3. Whole mix stretched to {SP}× with `atempo={SP}` (WSOLA, pitch unchanged): {LN['premaster_speed_lufs']:.1f} LUFS.",
     f"4. Master chain on the {SP}× file only: `{LN['master_chain']}`.",
     f"5. Two-pass loudnorm: pass 1 measured I {LN['pass1']['input_i']} LUFS / TP {LN['pass1']['input_tp']} dBTP; pass 2 type `{LN['pass2']['normalization_type']}`.", '',
     '## ffmpeg ebur128 on the master', '', '```', LN['ebur128_summary'], '```', '']
os.makedirs(os.path.join(EP, 'final'), exist_ok=True)
open(os.path.join(EP, 'final', 'loudnorm-report.md'), 'w').write('\n'.join(R))
print('CUE_SHEET.md, final/loudnorm-report.md, build/chapters.json written')
for t, n in CHAPTERS:
    print(m(t, False), n)
