"""Render the per-frame globe-spin basemaps -> render/cache/spin/f{frame}.jpg (not committed; regenerated by build).
Each frame: screen pixel -> plane (inverse of the exact camera homography from camera.js, dumped by dump_spins.mjs)
-> lon/lat (inverse orthographic about that frame's centre) -> the graded world texture (cache/equi.jpg, built by
make_basemap.py with the same grading as the static layers). 2x2 supersampled. Space outside the disc is the same
deep blue-black the static globe layers use; the limb glow is drawn by scenes.js."""
import json, os, sys, hashlib
import numpy as np
from PIL import Image
from scipy import ndimage as ndi
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from geo_common import inv  # noqa: E402
HERE = os.path.dirname(os.path.abspath(__file__))
CACHE = os.path.join(HERE, '..', 'cache')
OUT = os.path.join(CACHE, 'spin')
os.makedirs(OUT, exist_ok=True)
cams = json.load(open(os.path.join(CACHE, 'spin_cams.json')))
EQ = np.asarray(Image.open(os.path.join(CACHE, 'equi.jpg')).convert('RGB')).astype(np.float32) / 255
EH, EW = EQ.shape[:2]
# pre-blur a little so the minified globe never shimmers
EQ = ndi.gaussian_filter(EQ, (0.7, 0.7, 0))
SPACE = np.array([0.008, 0.014, 0.04], np.float32)
W, H, SS = 1080, 1920, 2
ys, xs = np.mgrid[0:H * SS, 0:W * SS].astype(np.float32)
U = (xs + 0.5) / SS
V = (ys + 0.5) / SS
force = '--force' in sys.argv
if '--reverse' in sys.argv:
    cams = cams[::-1]  # a second worker can start from the other end; finished frames are skipped by key
for fr in cams:
    key = hashlib.md5(json.dumps(fr, sort_keys=True).encode()).hexdigest()[:10]
    p = os.path.join(OUT, f"f{fr['i']:05d}.jpg")
    tag = p + '.key'
    if not force and os.path.exists(p) and os.path.exists(tag) and open(tag).read() == key:
        continue
    M = np.array(fr['M'], np.float64).reshape(3, 3)
    Mi = np.linalg.inv(M)
    Xh = Mi[0, 0] * U + Mi[0, 1] * V + Mi[0, 2]
    Yh = Mi[1, 0] * U + Mi[1, 1] * V + Mi[1, 2]
    Wh = Mi[2, 0] * U + Mi[2, 1] * V + Mi[2, 2]
    ok = Wh > 1e-9
    X = np.where(ok, Xh / np.where(ok, Wh, 1), 1e9)
    Y = np.where(ok, Yh / np.where(ok, Wh, 1), 1e9)
    lon, lat, disk = inv(X, Y, fr['c'])
    disk = disk & ok
    px = (lon + 180) / 360 * EW - 0.5
    py = (90 - lat) / 180 * EH - 0.5
    img = np.empty((H * SS, W * SS, 3), np.float32)
    for k in range(3):
        img[..., k] = ndi.map_coordinates(EQ[..., k], [py, px], order=1, mode='grid-wrap')
    img = np.where(disk[..., None], img, SPACE)
    img = img.reshape(H, SS, W, SS, 3).mean((1, 3))
    Image.fromarray((np.clip(img, 0, 1) * 255 + 0.5).astype(np.uint8)).save(p, quality=90)
    open(tag, 'w').write(key)
    print('spin', fr['i'], flush=True)
