"""s32 basemap builder: GeoGlobeTales-grade satellite layers on three orthographic planes, open data only.
See geo_common.py for sources, projection and look locks.

  plane A (160E, 37S)   Tasman: globe, tasman, seaus (south-east Australia), cant (Canterbury), wlg (Cook Strait),
                        timaru (close), melb (Port Phillip close)
  plane B (118W, 33N)   California / Baja: globe, cal, tj (Tijuana close)
  plane M (178W, 4S)    master map / opening reveal: globe

Also writes the graded equirectangular world texture used by make_spin.py for the globe-spin frames:
  render/cache/equi.jpg (not committed; regenerated by this script).

Usage: python3 make_basemap.py [layer ...]     (TILES / NE / BMNG env vars; see geo_common.py)
"""
import json, math, os, sys
import numpy as np
from PIL import Image
from scipy import ndimage as ndi
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from geo_common import (PLANES, R, fwd, inv, elevation, bm_colour, fbm, ne_mask_plane, ne_mask_equi, hillshade,  # noqa: E402
                        ocean_colour, grade_land, soft_shoulder)

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, '..', 'assets')
CACHE = os.path.join(HERE, '..', 'cache')
os.makedirs(OUT, exist_ok=True)
os.makedirs(CACHE, exist_ok=True)

# name: (plane, bbox lon0, lon1, lat0, lat1 | None for the full disc, K px/km, terrarium zoom, close?)
LAYERS = {
    'A_globe':  ('A', None, 0.25, 5, False),
    'A_tasman': ('A', (138.0, 180.0, -50.5, -25.5), 0.8, 7, False),
    'A_seaus':  ('A', (142.0, 153.6, -32.6, -39.6), 2.6, 9, True),
    'A_cant':   ('A', (168.6, 174.6, -41.6, -46.6), 3.0, 9, True),
    'A_wlg':    ('A', (173.4, 176.6, -40.2, -42.3), 4.0, 10, True),
    'A_timaru': ('A', (170.65, 171.85, -43.9, -44.8), 10.0, 11, True),
    'A_melb':   ('A', (144.35, 145.45, -37.45, -38.3), 10.0, 11, True),
    'B_globe':  ('B', None, 0.25, 5, False),
    'B_cal':    ('B', (-125.5, -112.5, 30.0, 42.8), 1.4, 8, False),
    'B_tj':     ('B', (-117.35, -116.6, 32.25, 32.78), 8.0, 11, True),
    'M_globe':  ('M', None, 0.25, 5, False),
}


def plane_bbox(name):
    pl, bb = LAYERS[name][0], LAYERS[name][1]
    if bb is None:
        return -R, R, -R, R
    lo = np.linspace(bb[0], bb[1], 80)
    la = np.linspace(bb[2], bb[3], 80)
    LO, LA = np.meshgrid(lo, la)
    X, Y, _ = fwd(LO, LA, PLANES[pl])
    return X.min(), X.max(), Y.min(), Y.max()


def grade_tile(lon, lat, X, Y, E, LANDM, K, close):
    """Colour for one block: land (BMNG + DEM light) and ocean (bathymetry navy)."""
    km_px = 1.0 / K
    El = np.where(LANDM > 0.5, np.maximum(E, 2.0), 0).astype(np.float32)
    hs_f = hillshade(ndi.gaussian_filter(El, 1.0), km_px, exag=1.1 if K >= 6 else (1.6 if close else 2.4))
    hs_b = hillshade(ndi.gaussian_filter(El, 4.0), km_px, exag=1.6 if K >= 6 else 3.0)
    col = bm_colour(lon, lat)
    detail = None
    if K >= 1.0:
        # field / scrub mottling so close views never look like an upscaled photo (deterministic, plane-anchored)
        detail = fbm(X, Y, K, 6, 3, 5) * 0.035 + fbm(X, Y, K, 60, 3, 9) * 0.03 + fbm(X, Y, K, 400, 2, 13) * 0.02
        lowland = np.clip(1 - El / 600.0, 0, 1)
        detail = detail * (0.4 + 0.6 * lowland)
    land = grade_land(col, El, hs_f, hs_b, detail)
    # ocean
    Ew = np.where(LANDM > 0.5, 0, E)
    sig = max(1.5, K * 3.0)
    DEP = ndi.gaussian_filter(np.maximum(-Ew, 0) + np.where(Ew > 0, 300, 0), sig).astype(np.float32)
    CDw = (ndi.distance_transform_edt(LANDM < 0.5) * km_px).astype(np.float32)
    DEP = np.minimum(DEP, 25 + CDw * 45.0)
    oc = ocean_colour(DEP)
    eb = ndi.gaussian_filter(np.minimum(Ew, 0), max(2.5, K * 5))
    bhs = hillshade(eb, km_px, exag=1.0)
    oc = oc * (1 + 0.15 * np.tanh(bhs / 0.04)[..., None])
    oc = oc * (1 + 0.05 * fbm(X, Y, K, 0.6, 4, 31)[..., None] + 0.03 * fbm(X, Y, K, 30, 4, 33)[..., None])
    # soft shallow halo right at the coast (sand / reef teal), only a few km wide
    halo = np.exp(-(CDw / (2.5 if close else 6.0)) ** 2)[..., None] * (1 - LANDM[..., None])
    oc = oc + halo * np.array([0.03, 0.06, 0.055])
    m = LANDM[..., None]
    out = land * m + oc * (1 - m)
    return np.clip(out, 0, 1)


def land_mask(name, c, x0, y0, K, W, H, E, XX, YY):
    close = LAYERS[name][4]
    if LAYERS[name][1] is None:
        # whole-disc layers: sample the equirectangular mask (polygons that wrap the far side of the globe
        # cannot be filled reliably in the plane)
        LON, LAT, _ = inv(XX, YY, c)
        m = equi_land()
        h, w = m.shape
        return ndi.map_coordinates(m, [(90 - LAT) / 180 * h - 0.5, (LON + 180) / 360 * w - 0.5], order=1, mode='grid-wrap').astype(np.float32)
    M = ne_mask_plane(['ne_10m_land', 'ne_10m_minor_islands'], c, x0, y0, K, W, H)
    lakes = ne_mask_plane(['ne_10m_lakes'], c, x0, y0, K, W, H)
    if close:
        # close views: the coastline comes from the 30-90 m DEM (land > ~1 m), constrained near Natural Earth's
        # generalised coast so DEM noise far offshore / inland never flips. Crisper bays, spits and estuaries.
        near = ndi.distance_transform_edt(np.abs(M - 0.5) > 0.45) / K  # km from the NE coast line
        dem_land = np.clip((E + 0.2) / 1.2, 0, 1)
        w = np.clip(1 - (near - 2.0) / 3.0, 0, 1)  # trust the DEM within ~2-5 km of the NE coast
        M = M * (1 - w) + dem_land * w
        M = ndi.gaussian_filter(M, 0.6)
        M = np.clip((M - 0.5) * 3 + 0.5, 0, 1)
    M = np.clip(M - lakes, 0, 1)
    return M.astype(np.float32)


_EL = None


def equi_land(W=8192):
    global _EL
    if _EL is None:
        _EL = np.clip(ne_mask_equi(['ne_10m_land', 'ne_10m_minor_islands'], W, W // 2) - ne_mask_equi(['ne_10m_lakes'], W, W // 2), 0, 1)
    return _EL


def build(name):
    pl, bb, K, z, close = LAYERS[name]
    c = PLANES[pl]
    x0, x1, y0, y1 = plane_bbox(name)
    W = int(round((x1 - x0) * K))
    H = int(round((y1 - y0) * K))
    print(name, W, 'x', H, f'K={K} px/km z{z}', flush=True)
    xs = x0 + (np.arange(W) + 0.5) / K
    ys = y0 + (np.arange(H) + 0.5) / K
    XX, YY = np.meshgrid(xs, ys)
    XX = XX.astype(np.float32)
    YY = YY.astype(np.float32)
    LON, LAT, DISK = inv(XX, YY, c)
    E = np.zeros_like(XX)
    if bb is None:
        E[DISK] = elevation(z, LON[DISK], LAT[DISK])
    else:
        E = elevation(z, LON, LAT).astype(np.float32)
        if z > 7:
            # Terrarium carries no bathymetry at high zooms (ocean reads 0 m): take the sea floor from z7
            Eb = elevation(7, LON, LAT).astype(np.float32)
            E = np.where(E > 0.25, E, np.minimum(Eb, -1.0))
    LANDM = land_mask(name, c, x0, y0, K, W, H, E, XX, YY)
    img = grade_tile(LON, LAT, XX, YY, E, LANDM, K, close)
    if bb is None:
        d = DISK[..., None]
        img = img * d + np.array([0.008, 0.014, 0.04]) * (1 - d)
    Image.fromarray((np.clip(img, 0, 1) * 255 + 0.5).astype(np.uint8)).save(
        os.path.join(OUT, f'map_{name}.jpg'), quality=86, subsampling=0, optimize=True, progressive=True)
    return dict(plane=pl, x0=float(x0), y0=float(y0), K=K, w=W, h=H, src=f'assets/map_{name}.jpg')


def build_equi(W=8192):
    """Graded equirectangular world texture (lon -180..180, lat 90..-90) for the spin renders."""
    H = W // 2
    print('equi', W, 'x', H, flush=True)
    lon = -180 + (np.arange(W) + 0.5) * 360 / W
    lat = 90 - (np.arange(H) + 0.5) * 180 / H
    LO, LA = np.meshgrid(lon.astype(np.float32), lat.astype(np.float32))
    E = elevation(5, LO, LA).astype(np.float32)
    LANDM = ne_mask_equi(['ne_10m_land', 'ne_10m_minor_islands'], W, H)
    lakes = ne_mask_equi(['ne_10m_lakes'], W, H)
    LANDM = np.clip(LANDM - lakes, 0, 1)
    kmx = (40075.0 / W) * np.maximum(np.cos(np.radians(LA)), 0.05)
    kmy = 40075.0 / 2 / H
    # pseudo plane coords for the procedural ocean texture (km, equal-ish)
    X = LO * 111.0 * np.cos(np.radians(LA))
    Y = -LA * 111.0
    K = 1.0 / kmy
    El = np.where(LANDM > 0.5, np.maximum(E, 2.0), 0).astype(np.float32)

    def hs_e(e, exag):
        g_row, g_col = np.gradient(e * exag)
        gx = g_col / (kmx * 1000)
        gy = -g_row / (kmy * 1000)
        n = np.sqrt(gx * gx + gy * gy + 1)
        azr, altr = math.radians(315), math.radians(40)
        lx, ly, lz = math.sin(azr) * math.cos(altr), math.cos(azr) * math.cos(altr), math.sin(altr)
        return (-gx * lx - gy * ly + lz) / n - lz

    out = np.zeros((H, W, 3), np.float32)
    col = bm_colour(LO, LA)
    land = grade_land(col, El, hs_e(ndi.gaussian_filter(El, 0.9), 2.4), hs_e(ndi.gaussian_filter(El, 4.0), 3.0), None)
    Ew = np.where(LANDM > 0.5, 0, E)
    DEP = ndi.gaussian_filter(np.maximum(-Ew, 0) + np.where(Ew > 0, 300, 0), 2.0).astype(np.float32)
    CDw = (ndi.distance_transform_edt(LANDM < 0.5) * kmy).astype(np.float32)
    DEP = np.minimum(DEP, 25 + CDw * 45.0)
    oc = ocean_colour(DEP)
    eb = ndi.gaussian_filter(np.minimum(Ew, 0), 3.0)
    oc = oc * (1 + 0.15 * np.tanh(hs_e(eb, 1.0) / 0.04)[..., None])
    oc = oc * (1 + 0.05 * fbm(X, Y, K, 0.6, 4, 31)[..., None])
    halo = np.exp(-(CDw / 6.0) ** 2)[..., None] * (1 - LANDM[..., None])
    oc = oc + halo * np.array([0.03, 0.06, 0.055])
    m = LANDM[..., None]
    out = np.clip(land * m + oc * (1 - m), 0, 1)
    Image.fromarray((out * 255 + 0.5).astype(np.uint8)).save(os.path.join(CACHE, 'equi.jpg'), quality=92)


if __name__ == '__main__':
    names = sys.argv[1:] or (list(LAYERS) + ['equi'])
    meta_p = os.path.join(OUT, 'map_layers.json')
    meta = json.load(open(meta_p)) if os.path.exists(meta_p) else {}
    for n in names:
        if n == 'equi':
            build_equi()
            continue
        meta[n] = build(n)
    meta = {k: meta[k] for k in LAYERS if k in meta}
    json.dump(meta, open(meta_p, 'w'), indent=1)
